services:
  - type: web
    name: restaurant-desktop-app
    env: node
    region: singapore
    plan: free
    buildCommand: npm install --prefix backend && npm install --prefix appss/web && npm run build --prefix appss/web
    startCommand: node backend/server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
